name: Check Bili Username Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-bili-username:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests cryptography

      - name: Run script
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          UID: ${{ secrets.UID }}
          EXPECTED_NAME: ${{ secrets.EXPECTED_NAME }}
        run: |
          python run.py
